# Generated by Django 2.2.2 on 2019-07-26 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verity',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='verity',
            name='mobile',
            field=models.CharField(default='0', max_length=11, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='0', max_length=30, verbose_name='手机号'),
        ),
    ]
